name: markdown-it-mermaid

channels:
  - conda-forge
  - nodefaults

dependencies:
  - docutils >=0.18
  - myst-parser
  - nodejs >=16,<17
  - pydata-sphinx-theme >=0.10.0,<0.11
  - python >=3.10,<3.11
  - sphinx >=5
  - sphinx-copybutton
